### ISSUE TITLE
Error activating addon on blender 3.0

### ISSUE THREAD

**Issue by SphinxRa40** [crapola/blender_t3d#1]
![2023-02-10 13_57_28-Blender](https://user-images.githubusercontent.com/41514794/218098271-ee56086d-384b-409c-8a39-fcdb309c8ccb.png)

**Comment by SphinxRa40** [comment]
I read about the Lark python for in the lib folder, can you explain more specifically where to put it?
3.3/python/lib/ 
I tried the lark-parser to put there (folder) separate folders but no avail, what do we need to move/copy in the lib folder
from the link-parser-1.12.0 files?!

**Comment by crapola** [comment]
The easiest way to install Lark is to execute this script inside Blender, in the Scripting tab:
```
import pip
pip.main(["install","lark"])
```
and then check Window/Toggle System Console to see results.

**Comment by SphinxRa40** [comment]
thank you, error os gone :)

**Comment by chaosesqueteam** [comment]
Does this do subtractive t3d brushes?
