### ISSUE TITLE
XIII game t3d gives error upon importing

### ISSUE THREAD

**Issue by Cianez** [crapola/blender_t3d#3]
I've exported the map DM_Amos from the game XIII to .t3d and I get this error when I try to import it with your plugin (Unreal Tournament DM_Deck16][.t3d imports fine with no errors).
![immagine](https://github.com/crapola/blender_t3d/assets/46445923/7526fb71-ae5d-44f6-8d75-4c0304cd5773)
I don't know how to fix it or if the plugin is compatible with XIII's UE branch.

**Comment by crapola** [comment]
It crashed because it encountered a "PanCoeff" and tried to interpret it as Pan.
I assume it's unique to XIII and that, given the name, it's related to texturing, so I could try to make the script ignore it.

**Comment by Cianez** [comment]
> It crashed because it encountered a "PanCoeff" and tried to interpret it as Pan. I assume it's unique to XIII and that, given the name, it's related to texturing, so I could try to make the script ignore it.

Ah ok. It would be helpful if you could try that. Thank you.

**Comment by crapola** [comment]
I've found that PanCoeff is in fact a sound property and updated the script on the main branch.
