### ISSUE TITLE
type error abcmeta object is not subscripable

### ISSUE THREAD

**Issue by uksas** [crapola/blender_t3d#5]
its happens when i try to enable the addon i already downloaded lark pip but it happens
![hata](https://github.com/crapola/blender_t3d/assets/50269723/fd76af28-332f-4013-a93d-6ebac2d6cd1f)

**Comment by uksas** [comment]
Ok which version it works?

**Comment by crapola** [comment]
At least 3.3 LTS

**Comment by uksas** [comment]
![hatas](https://github.com/crapola/blender_t3d/assets/50269723/c4278f17-e32a-4d7c-82f2-435846d9c7a6)
i downloaded 3.3 and download pip and lark pip when i import file it gives that error are you have discord or something else for contact

**Comment by crapola** [comment]
Apparently a TextureU was followed by a "Subdivisions" keyword, which is unknown to me. I'd be curious to see that line 57784, and where the t3d comes from.

**Comment by uksas** [comment]
İts swat 4 map i try to port swat 4 maps for garry's mod

**Comment by uksas** [comment]
İ save as t3d whole map and try with your addon i export as . Stl but models dont have any uv map thats why i try my luck with t3d i got no choice for it, i dont know why but swat 4 editor saves without texture

**Comment by uksas** [comment]
İ also try with props and it give same error,i opened on unreal engine 3 and unreal engine 2 and re export
İt give same error

**Comment by crapola** [comment]
I see, so the Unreal 2 ParticleEmitter class has members called TextureUSubdivisions and TextureVSubdivisions.

**Comment by uksas** [comment]
[unreal 2 t3d examples.zip](https://github.com/crapola/blender_t3d/files/13908689/unreal.2.t3d.examples.zip)
here is some example of unreal engine 2 t3d files if you want to work on it,also it comes from 3 diffrent game for you find out whats different

**Comment by crapola** [comment]
Thanks. Commit 8b656c0 should take care of the crashes.

**Comment by uksas** [comment]
thank you so much for care my problem and fixing it works very well and uv map works,i was lose my hope about porting whole game

**Comment by uksas** [comment]
i found out something very weird in all map editors (not your addon's fault) when i exported map it only saves walls
